TodoApp/ViewModels/TimelineViewModels/CreateViewModel.cs
using System.ComponentModel.DataAnnotations;
using TodoApp.DAL;

namespace TodoApp.ViewModels.TimelineViewModels
{
    public class CreateViewModel
    {
        [Required]
        [Display(Name = "Description")]
        [RegularExpression("^[^<>@#%/]+$", ErrorMessage = "La description ne peut contenir les caractères : < > @ # % /")]
        public string Text { get; set; }
        [Required]
        public EntryType Type { get; set; }
    }
}

TodoApp/ViewModels/TodoViewModels/CreateViewModel.cs
using System.ComponentModel.DataAnnotations;
using TodoApp.DAL;

namespace TodoApp.ViewModels.TodoViewModels
{
    public class CreateViewModel
    {
        [Required]
        [Display(Name = "Priorité")]
        public Priority Priority { get; set; }
        [Required]
        [Display(Name = "Description")]
        [RegularExpression("^[^<>@#%/]+$", ErrorMessage = "La description ne peut contenir les caractères : < > @ # % /")]
        public string Text { get; set; }
        [Required]
        [RegularExpression("^[a-zA-Z0-9_ ]*$", ErrorMessage = "Le titre n'est pas valide, ne peut contenir que des lettres ou des chiffres.")]
        [Display(Name = "Titre")]
        [StringLength(32)]
        public string Title { get; set; }
    }
}

TodoApp/Controllers/TimelineController.cs
using System.Web.Mvc;
using TodoApp.DAL;
using TodoApp.Filters;
using TodoApp.ViewModels.TimelineViewModels;
using WebMatrix.WebData;

namespace TodoApp.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class TimelineController : Controller
    {
        private readonly TodoManager todoManager;

        public TimelineController()
        {
            todoManager = new TodoManager();
        }

        //
        // GET: /Timeline/Create/5
        [HttpGet]
        public ActionResult Create(int id)
        {
            ViewBag.Id = id;
            return PartialView();
        }

        //
        // POST: /Timeline/Create/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int id, CreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var timeline = new Timeline()
                {
                    Type = model.Type,
                    Text = model.Text
                };

                todoManager.Attach(WebSecurity.CurrentUserId, id, timeline);
            }
            return RedirectToAction("Details", "Todo", new { id = id });
        }

        //
        // GET: /Timeline/Details/5
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Details(int id)
        {
            var timeline = todoManager.FindTimelineByTodoId(id);
            if (timeline == null)
            {
                return HttpNotFound();
            }
            return PartialView(timeline);
        }
    }
}

TodoApp/Views/Timeline/Create.cshtml
@using TodoApp.DAL
@using TodoApp.Helper
@model TodoApp.ViewModels.TimelineViewModels.CreateViewModel

<h3>Ajouter une entrée</h3>
<div class="row">
    <div class="col-md-offset-3 col-md-6 col-md-offset-3">
        <div class="form-horizontal">
            @using (Html.BeginForm("Create", "Timeline", new { id = ViewBag.Id }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(false, "", new { @class = "text-danger" })

                @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label" })
                <div class="form-group">
                     @Html.EnumDropDownListFor(model => model.Type, new { @class = "btn btn-default" })
                </div>
        
                @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label" })
                <div class="form-group">
                     @Html.TextAreaFor(model => model.Text, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    <input class="btn btn-primary" type="submit" value="Ajouter" />
                </div>
            }
        </div>
    </div>
</div>

TodoApp/Views/Timeline/Details.cshtml
@using TodoApp.Helper
@using System.Collections.Generic
@model List<TodoApp.DAL.Timeline>

<ul class="timeline">
    @for (int i = 0; i < Model.Count(); i++) {
        
        <li class="@(i % 2 == 0 ? "" : "timeline-inverted")">
            @Html.Badge(Model[i])
            <div class="timeline-panel">
                <div class="timeline-heading">
                    <h4 class="timeline-title">@Model[i].User.UserName</h4>
                    <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> @Model[i].Date.ToUniversalTime()</small></p>
                </div>
                <div class="timeline-body">
                    <p>@Html.RawLine(Model[i].Text)</p>
                </div>
            </div>
        </li>     
    }
</ul>