TodoApp/Controllers/TodoController.cs
using System.Web.Mvc;
using TodoApp.DAL;
using TodoApp.Filters;
using TodoApp.ViewModels.TodoViewModels;
using WebMatrix.WebData;

namespace TodoApp.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class TodoController : Controller
    {
        private readonly TodoManager todoManager;

        public TodoController()
        {
            todoManager = new TodoManager();
        }

        //
        // GET: /Todo/
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Index()
        {
            return View(todoManager.ToList());
        }

        //
        // GET : /Todo/Completed
        [HttpGet]
        public ActionResult Completed(int id)
        {
            Todo todo = todoManager.FindTodoById(id);
            if (todo == null)
            {
                return HttpNotFound();
            }
            todoManager.Completed(id);
            return RedirectToAction("Index");
        }

        //
        // GET: /Todo/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Todo/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var todo = new Todo()
                {
                    Title = model.Title,
                    Text = model.Text,
                    Priority = model.Priority
                };

                todoManager.Create(WebSecurity.CurrentUserId, todo);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        //
        // GET: /Todo/Clear
        [HttpGet]
        public ActionResult Clear()
        {
            return View();
        }

        //
        // GET: /Todo/Details
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Details(int id)
        {
            Todo todo = todoManager.FindTodoById(id);
            if (todo == null)
            {
                return HttpNotFound();
            }
            return View(todo);
        }

        //
        // POST: /Todo/Clear
        [HttpPost, ActionName("Clear")]
        [ValidateAntiForgeryToken]
        public ActionResult ClearConfirmed()
        {
            todoManager.Clear();
            return RedirectToAction("Index");
        }

        //
        // GET: /Todo/Edit/5
        [HttpGet]
        public ActionResult Edit(int id = 0)
        {
            Todo todo = todoManager.FindTodoById(id);
            if (todo == null)
            {
                return HttpNotFound();
            }

            var model = new EditViewModel();
            model.Set(todo);

            return View(model);
        }

        //
        // POST: /Todo/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Todo todo = todoManager.FindTodoById(model.Id);
                if (todo == null)
                {
                    return HttpNotFound();
                }
                
                todo.Priority = model.Priority;
                todo.Progress = model.Progress;
                todo.Text = model.Text;
                todo.Title = model.Title;

                todoManager.Edit(todo);

                return RedirectToAction("Index");
            }
            return View(model);
        }

        //
        // GET: /Todo/Delete/5
        [HttpGet]
        public ActionResult Delete(int id = 0)
        {
            Todo todo = todoManager.FindTodoById(id);
            if (todo == null)
            {
                return HttpNotFound();
            }
            return View(todo);
        }

        //
        // POST: /Todo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Todo todo = todoManager.FindTodoById(id);
            if (todo == null)
            {
                return HttpNotFound();
            }

            todoManager.Remove(todo);

            return RedirectToAction("Index");
        }
    }
}

TodoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <meta name="description" content="The description of my page" />
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Mes Tâches", "Index", "Todo", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Todo")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tâche <b class="caret"></b> </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Nouvelle tâche", "Create", "Todo")</li>
                            <li>@Html.ActionLink("Supprimer tous", "Clear", "Todo")</li>
                        </ul>
                    </li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @Html.Partial("_LoginPartial")
                </ul>
            </div>
        </div>
    </nav>
    
    <div class="container">
        <div class="modal-content">
            <div class="modal-header" style="text-align: center">
                <h4 class="modal-title">@ViewBag.Title</h4>
            </div>
            <div class="modal-body" style="text-align: center">
                <div class="container" style="width:100%">
                    @RenderBody()
                </div>
            </div>
            <div class="modal-footer">
                <p>Copyright ® @DateTime.Now.Year</p>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>